container:
  image: python:latest

test_task:

  test_script:
    - pip install --upgrade pip
    - pip install distro
    - python -c 'import platform; print(platform.uname())'  # , platform.dist())'
    - python -c 'import geographiclib; print("geographiclib " + geographiclib.__version__)'
  

#
# OSX
#
osx_task:
  auto_cancellation: true

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  check_script:
    - python -c "import platform; print(platform.machine(), platform.architecture())"

