container:
  image: python:3.10


#
# OSX
#
osx_task:
  auto_cancellation: true

  matrix:
    env:
      PY_VER: "3.10"

  name: "OSX: py${PY_VER}"

  env:
    PATH: $HOME/miniconda3/bin/:$PATH

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  env:
    PATH: $HOME/miniconda3/bin/:$PATH

  check_script:
    - conda list
    - python -c "import platform; print(platform.machine(), platform.architecture())"

