container:
  image: python:latest

test_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    python3 -c 'import platform; print(platform.machine(), platform.uname())'  # , platform.dist())'
    brew install csound
    which csound
    python3 -m pip install risset
    risset list
    risset info
    risset install else beosc klib
    csound -z1 2>&1

    echo "Running macos tests..."
    bash test/macos-run-tests.sh

#
# OSX
#
#osx_task:
#  auto_cancellation: true

#
#  check_script:
#    - python3 -c "import platform; print(platform.machine(), platform.architecture())"

