container:
  image: python:latest

test_task:

  test_script:
    - pip install --upgrade pip
    - python3 -c 'import platform; print(platform.uname())'  # , platform.dist())'
  

#
# OSX
#
#osx_task:
#  auto_cancellation: true

#  macos_instance:
#    image: ghcr.io/cirruslabs/macos-ventura-base:latest
#
#  check_script:
#    - python3 -c "import platform; print(platform.machine(), platform.architecture())"

