container:
  image: python:latest

test_risset_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    python3 -c 'import platform; print(platform.machine(), platform.uname())'  # , platform.dist())'
    brew install csound
    which csound

    brew install pipx
    pipx ensurepath

    pipx install risset
    
    risset list
    risset info
    risset install else beosc klib

    echo "Running macos tests..."
    bash test/macos-run-tests.sh

    csound -z1 2>&1 ; echo finished

test_universal_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  
  test_script: |
    set -x
    ls -l
    brew install csound
    which csound
    file $(which csound)

    brew install pipx
    pipx ensurepath

    pipx install risset

    risset list
    risset info
    wget "https://github.com/csound-plugins/csound-plugins/releases/download/latest/csound-plugins--macos-universal.zip"
    7z x csound-plugins--macos-universal.zip
    cp libelse.dylib libbeosc.dylib libklib.dylib $HOME/Library/csound/6.0/plugins64
    risset dev codesign
      
    echo "Running macos tests..."
    bash test/macos-run-tests.sh

    csound -z1 2>&1 ; echo finished


#
# OSX
#
#osx_task:
#  auto_cancellation: true

#
#  check_script:
#    - python3 -c "import platform; print(platform.machine(), platform.architecture())"

