site_name: Csound Plugins
theme: readthedocs
extra_css:
    - css/syntax-highlighting.css
    
markdown_extensions:
    - codehilite:
        guess_lang: false
        use_pygments: true
    - admonition

use_directory_urls: false