#!/bin/bash
shopt -s globstar

echo -e "\n------------------\nFilling manual pages\n"
mypath=$(dirname $(realpath $0))
srcpath=$(realpath $mypath/../src)
parallel "$mypath"/_fill_manual_page.py --verbose ::: ${srcpath}/**/*.md_
