#!/bin/bash
mypath=$(dirname $(realpath $0))
srcpath=$(realpath $mypath/../src)
templatefiles=$(find "$srcpath" -name "*.md_")
for f in $templatefiles; do
    echo $f
    $mypath/fill-manual-page.py "$f"
done