#!/bin/bash

set -x

VERSION=$(cat ../VERSION.txt)

DROP=$(realpath ~/Downloads/drop.zip)

rootpath=$(realpath "$0")
root=$(realpath $(dirname "$rootpath")/..)

OUTPUTDIR=$(realpath ../release/v$VERSION)

mkdir -p $OUTPUTDIR

cd ~/tmp
rm -fr ~/tmp/drop*

cp "$DROP" ~/tmp
ls -l 

aunpack drop.zip
cd drop/Linux

LINUXZIP=csound-plugins--$VERSION--linux.zip
apack "$LINUXZIP" *
cp "$LINUXZIP" "$OUTPUTDIR"

cd ..
cd MacOS

MACOSZIP=csound-plugins--$VERSION--macOS.zip
apack "$MACOSZIP" *
cp "$MACOSZIP" "$OUTPUTDIR"


cd "$root"
scripts/cross-compile-win.sh
cd buildwin

WINZIP=csound-plugins--$VERSION--win64.zip
apack "$WINZIP" *
cp "$WINZIP" "$OUTPUTDIR"

echo "Binaries are in $OUTPUTDIR"
ls -l "$OUTPUTDIR"

echo "---------------------------"
echo " Making release in github"
echo "---------------------------"

git tag v$VERSION
git push --tags
gh release create v$VERSION $OUTPUTDIR/*