#!/bin/bash

VERSION=1.3.0
echo "VERSION: " $VERSION

DROP=$(realpath ~/Downloads/drop.zip)

rootpath=$(realpath "$0")
root=$(realpath $(dirname "$rootpath")/..)
echo $root

RISSETDATA=$(realpath ~/dev/csound/risset-data)

copydocs() {
    namespace="$1"
    plugin="$2"
    version="$3"
    mkdir -p $RISSETDATA/plugins/$namespace/$plugin/$version/doc
    mkdir -p $RISSETDATA/plugins/$namespace/$plugin/$version/doc/assets
                
    cp $root/src/$plugin/docs/*.md "$RISSETDATA"/plugins/$namespace/$plugin/$version/doc/
    cp $root/src/$plugin/docs/assets/* "$RISSETDATA"/plugins/$namespace/$plugin/$version/doc/assets

    $root/scripts/make-risset-manifest -o $RISSETDATA/plugins/$namespace/$plugin/$version/manifest.json \
        $root/src/$plugin/manifest.json 
            
}

copydocs emplugins else $VERSION
copydocs emplugins klib $VERSION
copydocs emplugins poly $VERSION
copydocs emplugins jsfx $VERSION
copydocs emplugins pathtools $VERSION

cd ~/tmp
rm -fr ~/tmp/drop*

cp "$DROP" ~/tmp
ls -l 
aunpack drop.zip
cd drop/Linux

for plugin in else klib poly jsfx pathtools; do
    mkdir -p $RISSETDATA/plugins/emplugins/$plugin/$VERSION && cp lib$plugin.so $RISSETDATA/plugins/emplugins/$plugin/$VERSION
done
mkdir -p $RISSETDATA/plugins/rorywalsh/rory/$VERSION
cp librory.so $RISSETDATA/plugins/rorywalsh/rory/$VERSION

cd ..
cd MacOS
for plugin in else klib poly jsfx pathtools; do
    cp lib$plugin.dylib $RISSETDATA/plugins/emplugins/$plugin/$VERSION
done
cp librory.dylib $RISSETDATA/plugins/rorywalsh/rory/$VERSION

cd "$root"
scripts/cross-compile-win.sh
cd buildwin

for plugin in else klib pathtools poly; do
    cp lib$plugin.dll "$RISSETDATA/plugins/emplugins/$plugin/$VERSION"
done
cp librory.dll "$RISSETDATA/plugins/rorywalsh/rory/$VERSION"

pushd
cd $RISSETDATA
scripts/generate-documentation.py --html
