#!/bin/bash

NAMESPACE=em

VERSION=$(cat ../VERSION.txt)
echo "VERSION: '$VERSION'"

rootpath=$(realpath "$0")
root=$(realpath $(dirname "$rootpath")/..)
echo $root

RISSETDATA=$(realpath ~/dev/csound/risset-data)

copydocs() {
    namespace="$1"
    plugin="$2"
    mkdir -p $RISSETDATA/plugins/$namespace/$plugin/doc
    mkdir -p $RISSETDATA/plugins/$namespace/$plugin/doc/assets
    cp $root/src/$plugin/docs/*.md "$RISSETDATA"/plugins/$namespace/$plugin/doc/
    cp $root/src/$plugin/docs/assets/* "$RISSETDATA"/plugins/$namespace/$plugin/doc/assets

    $root/scripts/make-risset-manifest -o $RISSETDATA/plugins/$namespace/$plugin/manifest.json \
        $root/src/$plugin/manifest.json
}

copydocs em else
copydocs em klib
copydocs em poly
copydocs em jsfx
copydocs em pathtools
copydocs em beosc

builddir=risset-data-build
cd ~/tmp
rm -fr "$builddir"
mkdir "$builddir"
cd "$builddir"

# Download latest release
REPO=csound-plugins/csound-plugins
curl -s https://api.github.com/repos/$REPO/releases/latest \
    | grep browser_download_url | cut -d : -f 2,3 | tr -d \" | wget -qi -

ls -l *.zip

aunpack csound-plugins--linux.zip
for plugin in else klib poly jsfx pathtools beosc; do
    mkdir -p $RISSETDATA/plugins/em/$plugin
    cp csound-plugins--linux/lib$plugin.so $RISSETDATA/plugins/em/$plugin/
done

aunpack csound-plugins--macos.zip
for plugin in else klib poly jsfx pathtools beosc; do
    mkdir -p $RISSETDATA/plugins/em/$plugin
    cp csound-plugins--macos/lib$plugin.dylib $RISSETDATA/plugins/em/$plugin/
done

aunpack csound-plugins--win64.zip
for plugin in else klib poly pathtools beosc; do
    mkdir -p $RISSETDATA/plugins/em/$plugin
    cp csound-plugins--win64/$plugin.dll $RISSETDATA/plugins/em/$plugin/
done

cd $RISSETDATA
scripts/generate-documentation.py --html
