name: Build

on:
  push

jobs:
  build:
    name: Build plugins on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2

      - name: windows build
        if: runner.os == 'windows'
        run: |
          # where.exe vcpkg
          vcpkg integrate install
          vcpkg install libsndfile:x64-windows
          vcpkg list
          
          git submodule update --init --recursive --remote
          git submodule foreach git pull origin master
          git submodule status --recursive

          rm -r -fo build-windows
          mkdir build-windows
          cd build-windows

          rm -r -fo Release

          cmake -A x64 -DBUILD_JSUSFX_OPCODES=OFF -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows ..
          cmake --build . --config Release

          set-variable -name ARCHIVE -value "csound-plugins--win64.zip"
          if (Test-Path $ARCHIVE) {
            Remove-Item $ARCHIVE
          }
          7z a $ARCHIVE Release/*.dll
          7z l $ARCHIVE
          