name: Test plugins
on: push
jobs:
  testjob6:
    name: Test plugins on ${{ matrix.os }} (csound 6)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-2019, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: linux build and test
        if: runner.os == 'linux'
        run: |
          set -x

          sudo cp /etc/apt/sources.list /etc/apt/sources.list~
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update


          #sudo apt-get install csound

          sudo apt-get build-dep csound
          sudo apt-get install cmake
          git clone -b csound6 https://github.com/csound/csound.git csound
          cd csound
          mkdir build && cd build
          cmake ..
          cmake --build . --parallel
          sudo cmake --install .
          sudo ldconfig
          cd ../..

          sudo apt-get install libsndfile1-dev nasm
          # sudo apt-get install libfluidsynth-dev

          git submodule update --init --recursive --remote
          # git submodule foreach git pull origin master --rebase
          git submodule status --recursive
          # cd csound
          # git switch csound6
          # cd ..

          # cd csound/include
          # ln -s ../Android/CsoundAndroid/jni/version.h .
          # cd ../..

          rm -fr build-linux
          mkdir build-linux
          cd build-linux

          cmake -DSKIP_FAST_MATH=True ..
          # cmake ..
          cmake --build . --parallel
          cmake --install .

          cd ..
          mkdir -p artifacts
          
          cd src/beosc/examples
          csound -o beadsynt.wav beadsynt.csd
          ls *.wav
          cp beadsynt.wav ../../../artifacts

          cd ../../..
          ls artifacts/*
          

      - uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: artifacts/*

